### ISSUE TITLE
How to disable proactive mode of operation?

### ISSUE THREAD

**Issue by ababo** [smasherprog/screen_capture_lite#77]
I would like to capture frames on demand, without using your timer and callbacks under the hood. Is that supported? Thanks.

**Comment by smasherprog** [comment]
To answer your question: No, I dont believe anyone would use it.
Whats your use-case?
Your asking for a blocking version of this. This sounds good on the surface, but the time to retrieve the frames would vary widely due to the Waiting which must occur, and on both windows and mac these versions consume a significantly higher amount of CPU as well -- a different between 5% and like 30% usage so I didnt implement them. This again is due the synchronization which occurs in the OS and in this library while it waits for the data from the OS.

**Comment by smasherprog** [comment]
If u want to do a PR for this, i'd be open to it!

**Comment by smasherprog** [comment]
Gonna close this soon if we cant start a dialog on this

**Comment by ababo** [comment]
The problem is that my code base is based on maintaining threads and timers itself instead of relying on a third party. So I have added a workaround at the cost of excess copying. Feel free to close the issue, but I'm still confident the library should provide direct access to screen capture instead of (or in addition to) passing callbacks.

**Comment by smasherprog** [comment]
I hear you... Ill create a blocking version of this, its actually not too bad to write the code.
Ill see what I can do in the next few days.

**Comment by smasherprog** [comment]
If you want to take a stab at it and do a PR that would be cool too 👍

**Comment by smasherprog** [comment]
Im gonna close this as trying to grab a screen shot on demand is beyond the scope of this project. 
This library is event driven which gives the greatest performance. If a blocking version is required. PR's are accepted!
